export default {
    login: 'maxkram',
    id: 7889219,
    node_id: 'MDQ6VXNlcjc4ODkyMTk=',
    avatar_url: 'https://avatars.githubusercontent.com/u/7889219?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/maxkram',
    html_url: 'https://github.com/maxkram',
    followers_url: 'https://api.github.com/users/maxkram/followers',
    following_url:
        'https://api.github.com/users/maxkram/following{/other_user}',
    gists_url: 'https://api.github.com/users/maxkram/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/maxkram/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/maxkram/subscriptions',
    organizations_url: 'https://api.github.com/users/maxkram/orgs',
    repos_url: 'https://api.github.com/users/maxkram/repos',
    events_url: 'https://api.github.com/users/maxkram/events{/privacy}',
    received_events_url: 'https://api.github.com/users/maxkram/received_events',
    type: 'User',
    site_admin: false,
    name: 'Max Kramer',
    company: 'Atem',
    blog: 'https://maxkram.netlify.app/',
    location: 'Toronto',
    email: null,
    hireable: null,
    bio: '',
    twitter_username: 'mxkrm',
    public_repos: 112,
    public_gists: 0,
    followers: 1,
    following: 0,
    created_at: '2017-03-06T06:48:23Z',
    updated_at: '2022-07-08T05:01:32Z',
};
